### ISSUE TITLE
[PE-D][Tester A] Typo in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T12-4/tp#144]
![image.png](https://raw.githubusercontent.com/Khaleelur-Rahman/ped/main/files/ffd0e91a-8591-4dec-a25b-13bb3633e7c0.png)

As attached, `fied` has a typo. 

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: Khaleelur-Rahman/ped#17

**Comment by Clin-lyx** [comment]
done
